/**
 * static-energy — branching electrical arcs that strike, flicker and die.
 *
 * Arcs are generated by midpoint displacement: take a line, push its centre
 * sideways by a random amount, recurse on both halves, halving the
 * displacement each time. It is the same algorithm as fractal terrain, run
 * on a line instead of a grid, and it is what gives lightning its
 * characteristic jaggedness at every scale. Branches fork off with a
 * probability check at each subdivision.
 */

export const params = {
  arcCount: { kind: 'stepper', label: 'Arcs', min: 1, max: 12, step: 1, default: 3 },
  detail: { kind: 'stepper', label: 'Detail', min: 2, max: 8, step: 1, default: 6, hint: 'Subdivision depth. Each step doubles the segment count.' },
  displacement: { kind: 'slider', label: 'Jaggedness', min: 0, max: 1, step: 0.02, default: 0.42, modulatable: true },
  branchChance: { kind: 'slider', label: 'Branch chance', min: 0, max: 0.8, step: 0.02, default: 0.28 },
  branchDecay: { kind: 'slider', label: 'Branch decay', min: 0.2, max: 0.95, step: 0.02, default: 0.62, hint: 'How much shorter and dimmer each fork is than its parent.' },
  strikeRate: { kind: 'slider', label: 'Strike rate', min: 0.2, max: 12, step: 0.1, default: 3, modulatable: true, unit: '/s' },
  lifetime: { kind: 'slider', label: 'Arc lifetime', min: 0.05, max: 1.5, step: 0.05, default: 0.35, unit: 's' },
  flicker: { kind: 'slider', label: 'Flicker', min: 0, max: 1, step: 0.02, default: 0.55 },
  travel: { kind: 'select', label: 'Direction', default: 'radial', options: [
    { value: 'horizontal', label: 'Horizontal' },
    { value: 'vertical', label: 'Vertical' },
    { value: 'radial', label: 'From centre' },
    { value: 'pointer', label: 'From pointer' },
  ] },
  weight: { kind: 'slider', label: 'Core weight', min: 0.5, max: 6, step: 0.1, default: 1.6 },
  glow: { kind: 'slider', label: 'Glow', min: 0, max: 1, step: 0.02, default: 0.7 },
  fieldNoise: { kind: 'slider', label: 'Static field', min: 0, max: 1, step: 0.02, default: 0.25, hint: 'Background speckle between strikes.' },
  coreColor: { kind: 'color', label: 'Core', default: { r: 1, g: 1, b: 1, a: 1 } },
  glowColor: { kind: 'color', label: 'Glow', default: { r: 0, g: 0.83, b: 1, a: 1 } },
  reseed: { kind: 'trigger', label: 'Strike now', default: null, event: 'reseed', advanced: true, midi: false },
};

export default function sketch(p, get) {
  let arcs = [];
  let nextStrike = 0;

  function midpointPath(x1, y1, x2, y2, depth, disp) {
    let pts = [{ x: x1, y: y1 }, { x: x2, y: y2 }];
    let d = disp;
    for (let s = 0; s < depth; s++) {
      const next = [pts[0]];
      for (let i = 0; i < pts.length - 1; i++) {
        const a = pts[i], b = pts[i + 1];
        const mx = (a.x + b.x) / 2, my = (a.y + b.y) / 2;
        const dx = b.x - a.x, dy = b.y - a.y;
        const len = Math.hypot(dx, dy) || 1;
        // Displace perpendicular to the segment.
        const off = (Math.random() - 0.5) * d * len;
        next.push({ x: mx + (-dy / len) * off, y: my + (dx / len) * off });
        next.push(b);
      }
      pts = next;
      d *= 0.55;
    }
    return pts;
  }

  function makeArc() {
    const mode = get('travel');
    let x1, y1, x2, y2;

    if (mode === 'horizontal') {
      y1 = Math.random() * p.height; y2 = Math.random() * p.height;
      x1 = 0; x2 = p.width;
    } else if (mode === 'vertical') {
      x1 = Math.random() * p.width; x2 = Math.random() * p.width;
      y1 = 0; y2 = p.height;
    } else {
      const inside = mode === 'pointer' && p.mouseX > 0 && p.mouseX < p.width && p.mouseY > 0 && p.mouseY < p.height;
      x1 = inside ? p.mouseX : p.width / 2;
      y1 = inside ? p.mouseY : p.height / 2;
      const a = Math.random() * Math.PI * 2;
      const r = Math.max(p.width, p.height) * (0.35 + Math.random() * 0.35);
      x2 = x1 + Math.cos(a) * r;
      y2 = y1 + Math.sin(a) * r;
    }

    const depth = Math.floor(get('detail'));
    const disp = get('displacement');
    const branches = [];
    const main = midpointPath(x1, y1, x2, y2, depth, disp);

    const chance = get('branchChance');
    const decay = get('branchDecay');
    for (let i = 2; i < main.length - 2; i++) {
      if (Math.random() > chance) continue;
      const a = main[i];
      const ang = Math.random() * Math.PI * 2;
      const len = Math.hypot(x2 - x1, y2 - y1) * decay * (0.2 + Math.random() * 0.3);
      branches.push({
        pts: midpointPath(a.x, a.y, a.x + Math.cos(ang) * len, a.y + Math.sin(ang) * len, Math.max(1, depth - 2), disp),
        dim: decay,
      });
    }

    return { main, branches, born: p.millis() / 1000, seed: Math.random() * 100 };
  }

  p.setup = () => {
    p.createCanvas(p.windowWidth, p.windowHeight);
    p.colorMode(p.RGB, 1, 1, 1, 1);
    p.noFill();
  };

  p.windowResized = () => p.resizeCanvas(p.windowWidth, p.windowHeight);
  p.onEvent = (name) => { if (name === 'reseed') arcs.push(makeArc()); };

  p.draw = () => {
    p.background(0);

    const now = p.millis() / 1000;
    const life = get('lifetime');
    const rate = get('strikeRate');

    if (now >= nextStrike) {
      const want = Math.floor(get('arcCount'));
      for (let i = 0; i < want; i++) arcs.push(makeArc());
      nextStrike = now + 1 / Math.max(rate, 0.01);
    }

    arcs = arcs.filter((a) => now - a.born < life);

    const field = get('fieldNoise');
    if (field > 0) {
      p.noStroke();
      const glowC = get('glowColor');
      const dots = Math.floor(field * 260);
      for (let i = 0; i < dots; i++) {
        p.fill(glowC.r, glowC.g, glowC.b, Math.random() * field * 0.5);
        p.circle(Math.random() * p.width, Math.random() * p.height, Math.random() * 2 + 0.5);
      }
      p.noFill();
    }

    const core = get('coreColor');
    const glowC = get('glowColor');
    const weight = get('weight');
    const glow = get('glow');
    const flicker = get('flicker');

    const drawPath = (pts, alpha, w) => {
      p.beginShape();
      for (const q of pts) p.vertex(q.x, q.y);
      p.endShape();
    };

    for (const arc of arcs) {
      const age = (now - arc.born) / life;
      let alpha = 1 - age;
      if (flicker > 0) {
        alpha *= 1 - flicker * Math.abs(Math.sin((now + arc.seed) * 47));
      }
      if (alpha <= 0.01) continue;

      if (glow > 0) {
        p.stroke(glowC.r, glowC.g, glowC.b, alpha * glow * 0.25);
        p.strokeWeight(weight * 6);
        drawPath(arc.main);
        p.stroke(glowC.r, glowC.g, glowC.b, alpha * glow * 0.4);
        p.strokeWeight(weight * 3);
        drawPath(arc.main);
      }

      p.stroke(core.r, core.g, core.b, alpha);
      p.strokeWeight(weight);
      drawPath(arc.main);

      for (const b of arc.branches) {
        if (glow > 0) {
          p.stroke(glowC.r, glowC.g, glowC.b, alpha * b.dim * glow * 0.3);
          p.strokeWeight(weight * 2.2);
          drawPath(b.pts);
        }
        p.stroke(core.r, core.g, core.b, alpha * b.dim);
        p.strokeWeight(weight * 0.6);
        drawPath(b.pts);
      }
    }
  };
}
