#version 300 es
precision highp float;

/* ordered-dither — Bayer threshold matrices with palette quantisation.
   Bayer 2/4/8 are generated by recursion rather than stored as tables. */

uniform vec2 u_resolution;
uniform sampler2D u_src;       // @label(Source)

uniform int u_matrix;          // @label(Matrix) @select(Bayer 2x2=0 | Bayer 4x4=1 | Bayer 8x8=2 | Blue noise=3) @default(1)
uniform int u_paletteSize;     // @label(Palette steps) @range(2, 16) @default(3)
uniform float u_spread;        // @label(Spread) @range(0, 1) @default(0.55)
uniform float u_pixelSize;     // @label(Pixel size) @range(1, 16) @default(2) @log @unit(px)
uniform vec3 u_dark;           // @label(Dark) @color @default(0.02, 0.02, 0.03)
uniform vec3 u_light;          // @label(Light) @color @default(0.0, 0.83, 1.0)
uniform bool u_monochrome;     // @label(Monochrome) @default(true)
uniform bool u_serpentine;     // @label(Serpentine offset) @default(false) @advanced

out vec4 fragColor;

float bayer2(vec2 a) {
  a = floor(a);
  return fract(a.x / 2.0 + a.y * a.y * 0.75);
}

float bayer4(vec2 a) { return bayer2(0.5 * a) * 0.25 + bayer2(a); }
float bayer8(vec2 a) { return bayer4(0.5 * a) * 0.25 + bayer2(a); }

float hashNoise(vec2 p) {
  return fract(sin(dot(p, vec2(12.9898, 78.233))) * 43758.5453);
}

float threshold(vec2 p) {
  if (u_matrix == 0) return bayer2(p) / 0.75;
  if (u_matrix == 1) return bayer4(p) / 0.9375;
  if (u_matrix == 2) return bayer8(p) / 0.984375;
  return hashNoise(p);
}

void main() {
  vec2 px = floor(gl_FragCoord.xy / u_pixelSize);
  vec2 uv = (px * u_pixelSize + u_pixelSize * 0.5) / u_resolution;

  vec2 tp = px;
  if (u_serpentine && mod(px.y, 2.0) > 0.5) tp.x += 0.5;

  vec3 src = texture(u_src, uv).rgb;
  float t = (threshold(tp) - 0.5) * u_spread;

  float steps = float(max(u_paletteSize - 1, 1));
  vec3 v = u_monochrome ? vec3(dot(src, vec3(0.2126, 0.7152, 0.0722))) : src;
  vec3 q = floor(clamp(v + t, 0.0, 1.0) * steps + 0.5) / steps;

  fragColor = vec4(mix(u_dark, u_light, q), 1.0);
}
