-- Phase 4.96 — GPU Post-Processing Effects ("VFX")
-- Mirrors 0006_add_sound_presets.sql's shape exactly (a JSONB column on
-- assets, notNull default '[]', plus a nullable override column on
-- board_items) — same additive-only migration discipline as every other
-- column in this schema.
--
-- NOTE: this was hand-written to match the existing migrations' shape and
-- SQL style, not generated by drizzle-kit — I don't have drizzle-kit's
-- meta/_journal.json snapshot format in front of me, so this file's
-- CONTENT should be correct against schema.ts above, but you'll want to
-- run `drizzle-kit generate` for real (or diff this against what it
-- produces) rather than trusting this file's numbering/journal entry
-- blindly — see PLACEMENT.md.

ALTER TABLE "assets" ADD COLUMN IF NOT EXISTS "effects" jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE "board_items" ADD COLUMN IF NOT EXISTS "effects_override" jsonb;
