-- Auth hardening pass — password reuse history (lib/auth/password-history.ts).
-- See schema.auth.ts's own comment on this table for why the reuse cap
-- (HISTORY_SIZE) lives in application code, not a DB constraint here.
--
-- Hand-written to match this project's existing migration style (0006,
-- 0009), not generated by drizzle-kit — run `drizzle-kit generate` (or
-- diff this against its output) rather than trusting this file's
-- numbering/journal entry blindly, per those files' own notes. Content
-- here is written to match schema.auth.ts's passwordHistory table exactly.

CREATE TABLE IF NOT EXISTS "passwordHistory" (
  "id" text PRIMARY KEY,
  "userId" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "passwordHash" text NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "passwordHistory_userId_createdAt_idx" ON "passwordHistory" ("userId", "createdAt");
